services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        ports:
            - "9090:9090"
        volumes:
            - ./PromData:/prometheus/data
            - ./PromConf/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention.time=14d"
        depends_on:
            - snmp-exporter
            - blackbox-ping

    snmp-exporter:
        image: prom/snmp-exporter:latest
        container_name: snmp-exporter
        restart: unless-stopped
        ports:
            - "9116:9116"
        volumes:
            - ./SNMP/snmp.yml:/etc/snmp_exporter/snmp.yml

    blackbox-ping:
        image: prom/blackbox-exporter
        container_name: blackbox-ping
        ports:
            - "9115:9115"
        restart: unless-stopped
        command:
            - "--config.file=/etc/blackbox/blackbox.yml"
        volumes:
            - ./BlackboxICMP/blackbox.yml:/etc/blackbox/blackbox.yml
