services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        ports:
            - "9090:9090"
        volumes:
            - ./PromData:/prometheus/data
            - ./PromConf/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention.time=4w"
        depends_on:
            - blackbox-ping

    blackbox-ping:
        image: prom/blackbox-exporter
        container_name: blackbox-ping
        ports:
            - "9115:9115"
        restart: unless-stopped
        command:
            - "--config.file=/etc/blackbox/blackbox.yml"
        volumes:
            - ./BlackboxICMP/blackbox.yml:/etc/blackbox/blackbox.yml
